### ISSUE TITLE
你好，可以标出修改的地方吗，谢谢

### ISSUE THREAD

**Issue by HelloZhu** [a413107719/echarts-pie-roundcap#3]

**Comment by a413107719** [comment]
你好，因为第一次使用github所以不懂如何标记修改，我直接在这里进行回复。
编译后的echarts修改的地方为第14762行至14821行的sector >> buildPath方法。
具体目的是为了修改sector（扇形，因为echarts的饼图是用sector绘制的）的绘制方法。
你有两种方式可以实现此功能：
1、在build后但未混淆的echarts.js文件中替换sector >> buildPath方法；
2、直接修改node_modules\echarts\node_modules\zrender\src\graphic\shape\Sector.js中的sector >> buildPath方法，然后重新build
实际上就是因为echarts调用的是zrender中sector绘制方法，造成echarts自身难以实现环形饼图的roundCap。
具体代码块如下
```javascript
buildPath: function (ctx, shape) {
        var myDom = this.__zr.dom
        var myChart = echarts.getInstanceByDom(myDom)
        var seriesIndex = this.seriesIndex !== undefined ? this.seriesIndex : undefined
        var dataIndex = this.dataIndex !== undefined ? this.dataIndex : undefined
        var option = seriesIndex !== undefined ? myChart.getOption().series[seriesIndex] : undefined
        var roundCap = option ? option.roundCap : undefined
        var x = shape.cx;
        var y = shape.cy;
        var r0 = Math.max(shape.r0 || 0, 0);
        var r = Math.max(shape.r, 0);
        var startAngle = shape.startAngle;
        var endAngle = shape.endAngle;
        var clockwise = shape.clockwise;
        var unitX = Math.cos(startAngle);
        var unitY = Math.sin(startAngle);
        ctx.moveTo(unitX * r0 + x, unitY * r0 + y);
        if (!roundCap || r0 === 0){
            ctx.lineTo(unitX * r + x, unitY * r + y);
            ctx.arc(x, y, r, startAngle, endAngle, !clockwise);
            ctx.lineTo(Math.cos(endAngle) * r0 + x, Math.sin(endAngle) * r0 + y);
            if (r0 !== 0) {
                ctx.arc(x, y, r0, endAngle, startAngle, clockwise);
            }
        }
        else {
            var group = this.parent ? (this.parent.parent ? this.parent.parent : this.parent) : undefined
            var childrens = group.isGroup ? group.children() : []
            var normalR = undefined
            for (var idx = 0;idx<childrens.length;idx++){
                if (idx !== dataIndex && **(eval("childrens[idx] instanceof  PiePiece"))**){
                    normalR = childrens[idx]._children[0].shape.r
                }
            }
            var r1 = r0 + (r - r0) / 2
            var r2 = (r - r0) / 2
            var x1 = x + r1 * Math.cos(endAngle)
            var y1 = y + r1 * Math.sin(endAngle)
            var x2 = x + r1 * Math.cos(startAngle)
            var y2 = y + r1 * Math.sin(startAngle)
            if (normalR && normalR < r){
                ctx.arc(x2, y2, r2, startAngle+ Math.PI, startAngle, !clockwise);
            }
            else{
                ctx.arc(x2, y2, r2, startAngle+ Math.PI, startAngle, roundCap === 1 ? !clockwise :clockwise );
            }
            ctx.arc(x, y, r, startAngle, endAngle, !clockwise);
            ctx.arc(x1, y1, r2, endAngle, endAngle + Math.PI, !clockwise);
            if (r0 !== 0) {
                ctx.arc(x, y, r0, endAngle, startAngle, clockwise);
            }
        }
        ctx.closePath();
        // ctx._ctx ? ctx._ctx.stroke() : undefined;
      }
```

**Comment by HelloZhu** [comment]
> 你好，因为第一次使用github所以不懂如何标记修改，我直接在这里进行回复。
> 编译后的echarts修改的地方为第14762行至14821行的sector >> buildPath方法。
> 具体目的是为了修改sector（扇形，因为echarts的饼图是用sector绘制的）的绘制方法。
> 你有两种方式可以实现此功能：
> 1、在build后但未混淆的echarts.js文件中替换sector >> buildPath方法；
> 2、直接修改node_modules\echarts\node_modules\zrender\src\graphic\shape\Sector.js中的sector >> buildPath方法，然后重新build
> 实际上就是因为echarts调用的是zrender中sector绘制方法，造成echarts自身难以实现环形饼图的roundCap。
> 具体代码块如下
> buildPath: function (ctx, shape) {
> var myDom = this.__zr.dom
> var myChart = echarts.getInstanceByDom(myDom)
> var seriesIndex = this.seriesIndex !== undefined ? this.seriesIndex : undefined
> var dataIndex = this.dataIndex !== undefined ? this.dataIndex : undefined
> var option = seriesIndex !== undefined ? myChart.getOption().series[seriesIndex] : undefined
> var roundCap = option ? option.roundCap : undefined
> var x = shape.cx;
> var y = shape.cy;
> var r0 = Math.max(shape.r0 || 0, 0);
> var r = Math.max(shape.r, 0);
> var startAngle = shape.startAngle;
> var endAngle = shape.endAngle;
> var clockwise = shape.clockwise;
> var unitX = Math.cos(startAngle);
> var unitY = Math.sin(startAngle);
> ctx.moveTo(unitX * r0 + x, unitY * r0 + y);
> if (!roundCap || r0 === 0){
> ctx.lineTo(unitX * r + x, unitY * r + y);
> ctx.arc(x, y, r, startAngle, endAngle, !clockwise);
> ctx.lineTo(Math.cos(endAngle) * r0 + x, Math.sin(endAngle) * r0 + y);
> if (r0 !== 0) {
> ctx.arc(x, y, r0, endAngle, startAngle, clockwise);
> }
> }
> else {
> var group = this.parent ? (this.parent.parent ? this.parent.parent : this.parent) : undefined
> var childrens = group.isGroup ? group.children() : []
> var normalR = undefined
> for (var idx = 0;idx<childrens.length;idx++){
> if (idx !== dataIndex && **(eval("childrens[idx] instanceof PiePiece"))**){
> normalR = childrens[idx]._children[0].shape.r
> }
> }
> var r1 = r0 + (r - r0) / 2
> var r2 = (r - r0) / 2
> var x1 = x + r1 * Math.cos(endAngle)
> var y1 = y + r1 * Math.sin(endAngle)
> var x2 = x + r1 * Math.cos(startAngle)
> var y2 = y + r1 * Math.sin(startAngle)
> if (normalR && normalR < r){
> ctx.arc(x2, y2, r2, startAngle+ Math.PI, startAngle, !clockwise);
> }
> else{
> ctx.arc(x2, y2, r2, startAngle+ Math.PI, startAngle, roundCap === 1 ? !clockwise :clockwise );
> }
> ctx.arc(x, y, r, startAngle, endAngle, !clockwise);
> ctx.arc(x1, y1, r2, endAngle, endAngle + Math.PI, !clockwise);
> if (r0 !== 0) {
> ctx.arc(x, y, r0, endAngle, startAngle, clockwise);
> }
> }
> 
> ```
>     ctx.closePath();
>     // ctx._ctx ? ctx._ctx.stroke() : undefined;
>   }
> ```

第一次使用echart，非常感谢你的回复

**Comment by a413107719** [comment]
> > 你好，因为第一次使用github所以不懂如何标记修改，我直接在这里进行回复。
> > 编译后的echarts修改的地方为第14762行至14821行的sector >> buildPath方法。
> > 具体目的是为了修改sector（扇形，因为echarts的饼图是用sector绘制的）的绘制方法。
> > 你有两种方式可以实现此功能：
> > 1、在build后但未混淆的echarts.js文件中替换sector >> buildPath方法；
> > 2、直接修改node_modules\echarts\node_modules\zrender\src\graphic\shape\Sector.js中的sector >> buildPath方法，然后重新build
> > 实际上就是因为echarts调用的是zrender中sector绘制方法，造成echarts自身难以实现环形饼图的roundCap。
> > 具体代码块如下
> > buildPath: function (ctx, shape) {
> > var myDom = this.__zr.dom
> > var myChart = echarts.getInstanceByDom(myDom)
> > var seriesIndex = this.seriesIndex !== undefined ? this.seriesIndex : undefined
> > var dataIndex = this.dataIndex !== undefined ? this.dataIndex : undefined
> > var option = seriesIndex !== undefined ? myChart.getOption().series[seriesIndex] : undefined
> > var roundCap = option ? option.roundCap : undefined
> > var x = shape.cx;
> > var y = shape.cy;
> > var r0 = Math.max(shape.r0 || 0, 0);
> > var r = Math.max(shape.r, 0);
> > var startAngle = shape.startAngle;
> > var endAngle = shape.endAngle;
> > var clockwise = shape.clockwise;
> > var unitX = Math.cos(startAngle);
> > var unitY = Math.sin(startAngle);
> > ctx.moveTo(unitX * r0 + x, unitY * r0 + y);
> > if (!roundCap || r0 === 0){
> > ctx.lineTo(unitX * r + x, unitY * r + y);
> > ctx.arc(x, y, r, startAngle, endAngle, !clockwise);
> > ctx.lineTo(Math.cos(endAngle) * r0 + x, Math.sin(endAngle) * r0 + y);
> > if (r0 !== 0) {
> > ctx.arc(x, y, r0, endAngle, startAngle, clockwise);
> > }
> > }
> > else {
> > var group = this.parent ? (this.parent.parent ? this.parent.parent : this.parent) : undefined
> > var childrens = group.isGroup ? group.children() : []
> > var normalR = undefined
> > for (var idx = 0;idx<childrens.length;idx++){
> > if (idx !== dataIndex && **(eval("childrens[idx] instanceof PiePiece"))**){
> > normalR = childrens[idx]._children[0].shape.r
> > }
> > }
> > var r1 = r0 + (r - r0) / 2
> > var r2 = (r - r0) / 2
> > var x1 = x + r1 * Math.cos(endAngle)
> > var y1 = y + r1 * Math.sin(endAngle)
> > var x2 = x + r1 * Math.cos(startAngle)
> > var y2 = y + r1 * Math.sin(startAngle)
> > if (normalR && normalR < r){
> > ctx.arc(x2, y2, r2, startAngle+ Math.PI, startAngle, !clockwise);
> > }
> > else{
> > ctx.arc(x2, y2, r2, startAngle+ Math.PI, startAngle, roundCap === 1 ? !clockwise :clockwise );
> > }
> > ctx.arc(x, y, r, startAngle, endAngle, !clockwise);
> > ctx.arc(x1, y1, r2, endAngle, endAngle + Math.PI, !clockwise);
> > if (r0 !== 0) {
> > ctx.arc(x, y, r0, endAngle, startAngle, clockwise);
> > }
> > }
> > ```
> >     ctx.closePath();
> >     // ctx._ctx ? ctx._ctx.stroke() : undefined;
> >   }
> > ```
> 
> 第一次使用echart，非常感谢你的回复

不客气~

**Comment by xxx123123** [comment]
你好，在提出问题之前，我参与开发的项目是react（一系列技术栈），按照您提供的修改方式，我修改node_modules\echarts\node_modules\zrender\src\graphic\shape\Sector.js中的sector >> buildPath方法，并打包之后。
    导致报“echarts is not defined”， 错误直接指向 var myChart = echarts.getInstanceByDom(myDom)；
请问您这边遇到过这种情况吗？？？

**Comment by a413107719** [comment]
说明在react中echarts模块的全局名称可能不是echarts哦，
var myChart = echarts.getInstanceByDom(myDom)；目的是为了定位到当前echarts实例。
你可以看下react echarts的对应手册看下如何通过html dom获取echarts实例，替换上面错误语句应该就可以了。



在 2020-07-03 16:14:19，"xxx123123" <notifications@github.com> 写道：

你好，在提出问题之前，我参与开发的项目是react（一系列技术栈），按照您提供的修改方式，我修改node_modules\echarts\node_modules\zrender\src\graphic\shape\Sector.js中的sector >> buildPath方法，并打包之后。
导致报“echarts is not defined”， 错误直接指向 var myChart = echarts.getInstanceByDom(myDom)；
请问您这边遇到过这种情况吗？？？

**Comment by 863062879** [comment]
厉害   解决了我的问题  非常感谢
